### ISSUE TITLE
add env var support

### ISSUE THREAD

**Issue by Macleykun** [penguintutor/pixel-server#4]
I think it would be great to be able to use env vars instead of a config file!

It would make it also easier to use with my docker implementation :D

**Comment by penguintutor** [comment]
The implementation is really designed for simple Raspberry Pi setups. It is really designed to be the only app running on the system and so doesn't need to be in a container image. 

I do hope to provide a simpler install in future, but that is likely to be either through an debian package or perhaps through PIP. I need to add additional features before I consider that, including additional security. That will continue with a configuration file to be easier to include in the package and simple for those wishing to setup on a dedicated Raspberry Pi server.
