### ISSUE TITLE
Where is Auth.cfg?

### ISSUE THREAD

**Issue by Macleykun** [penguintutor/pixel-server#7]
Heya, i'm trying to update my container with your latest changes, but i keep getting:
![image](https://user-images.githubusercontent.com/26381427/188307736-9867394f-d356-48f8-817f-cab92f34b1e4.png)
I want to try to turn off auth, as i'm using cloudflare to login into the domain.

**Comment by penguintutor** [comment]
The auth.cfg file is not included as it could potentially override a users configuration. 

I have now changed the authentication to require login by default (more secure that allowing unauthenticated by default) and an example is now included in the README.md file.

**Comment by Macleykun** [comment]
Thank you so much! I now understand it a lot better and think I can set up a default user for the PR (or even for my own if it wouldn't get merged in the end).
