### ISSUE TITLE
Suggestion: Make pink color more pink

### ISSUE THREAD

**Issue by Macleykun** [penguintutor/pixel-server#8]
Currently, I noticed that all the colors look great! Except for pink looks more white than pink.

Current: #ffc0cb
![image](https://user-images.githubusercontent.com/26381427/188314508-31d9ea2a-ec31-4fd0-9884-e4331e5c7334.png)

Could be replaced with some more neon-pink like:
#ff66cc
![image](https://user-images.githubusercontent.com/26381427/188314536-b8d455c2-db07-47a2-9663-b6aa3209c6b3.png)

I did notice that CheerLights also uses this hex code for pink, but I wanted to suggest it anyways. I do understand if this gets immediately closed b/c it's not a good feature request.

**Comment by penguintutor** [comment]
Thanks for the suggestion. I had used the html default pink, but it is a bit too white. I was planning to tune the colour, but hadn't had chance.

Now updated.

**Comment by Macleykun** [comment]
> Thanks for the suggestion. I had used the html default pink, but it is a bit too white. I was planning to tune the colour, but hadn't had chance.
> 
> Now updated.

thank you yet again for this :) i did try it out and saw it changed on the frontend! With a dark background it looks great imo:
![image](https://user-images.githubusercontent.com/26381427/188332058-8ff7d8cc-81cd-49b4-8365-6d540cbe6ecd.png)

the pink looks lovely now :) i didn't think it would be possible to due color conventions! Massive thank you <3 !
